server:
  port: 8081
spring:
  application:
    name: feign-server
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/
sms:
  ip: 192.168.0.12
